services:
  - type: web
    name: laravel-api
    runtime: docker
    repo: https://github.com/username/laravel-api
    branch: main
    plan: free
    envVars:
      - key: APP_KEY
        value: base64:F6+usfj7EbmbyCE/pgMEzvL2MFTSx5gnz22X2F/ic9Q=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: financetracker
        value: <database-name>
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value:
    dockerfilePath: ./Dockerfile
